trigger_configs:
  - name: default
  - name: swipe_threshold
    config:
      threshold: 50
  - name: pinch_out
    config:
      threshold: 1.2
  - name: pinch_in
    config:
      threshold: 0.75

triggers:
  - type: swipe
    direction: left
    fingers: 3
    trigger_on: end
    config: default
    command:
      - i3-msg
      - focus left
  - type: swipe
    direction: right
    fingers: 3
    trigger_on: end
    config: default
    command:
      - i3-msg
      - focus right
  - type: swipe
    direction: up
    fingers: 3
    trigger_on: end
    config: swipe_threshold
    command:
      - i3-msg
      - focus up
  - type: swipe
    direction: down
    fingers: 3
    trigger_on: end
    config: swipe_threshold
    command:
      - i3-msg
      - focus down
  - type: swipe
    direction: up
    fingers: 4
    trigger_on: end
    config: swipe_threshold
    command:
      - i3-msg
      - fullscreen enable
  - type: swipe
    direction: down
    fingers: 4
    trigger_on: end
    config: swipe_threshold
    command:
      - i3-msg
      - fullscreen disable
  - type: swipe
    direction: left
    fingers: 4
    trigger_on: repeat
    config: swipe_threshold
    command:
      - xdotool
      - key
      - ctrl+shift+Tab
  - type: swipe
    direction: right
    fingers: 4
    trigger_on: repeat
    config: swipe_threshold
    command:
      - xdotool
      - key
      - ctrl+Tab
  - type: pinch
    fingers: 2
    trigger_on: end
    config: pinch_out
    command:
      - notify-send
      - Test yaml pinch out 2 end
  - type: pinch
    fingers: 2
    trigger_on: end
    config: pinch_in
    command:
      - notify-send
      - Test yaml pinch in 2 end
